import Vue from "vue";
import {
  Tabbar,
  TabbarItem,
  Search,
  Swipe,
  SwipeItem,
  Icon,
  Tab,
  Tabs,
  Sidebar,
  SidebarItem,
  Cell,
  Empty,
  Button,
  Form,
  NavBar,
  Field,
  Notify,
  GoodsAction,
  GoodsActionButton,
  GoodsActionIcon,
  Sku,
  Card,
  SubmitBar,
  Tag,
  Checkbox,
  Stepper,
  Toast,
  Dialog
} from "vant";

// 这里没有使用Popup（没有进行路由跳转）
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Search);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Icon);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Sidebar);
Vue.use(SidebarItem);
Vue.use(Cell);
Vue.use(Empty);
Vue.use(Button);
Vue.use(Form);
Vue.use(NavBar);
Vue.use(Field);
Vue.use(Notify);
Vue.use(GoodsAction);
Vue.use(GoodsActionButton);
Vue.use(GoodsActionIcon);
Vue.use(Sku);
Vue.use(Card);
Vue.use(SubmitBar);
Vue.use(Tag);
Vue.use(Checkbox);
Vue.use(Stepper);
Vue.use(Toast);
Vue.use(Dialog);
